package seedu.address.ui;

import java.util.logging.Logger;

import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.input.Clipboard;
import javafx.scene.input.ClipboardContent;
import javafx.stage.Stage;
import seedu.address.commons.core.LogsCenter;

/**
 * Controller for a help page
 */
public class HelpWindow extends UiPart<Stage> {

    public static final String USERGUIDE_URL = "https://ay2526s2-cs2103t-w08-4.github.io/tp/UserGuide.html";

    public static final String HELP_MESSAGE =
            "User Guide:\n" + USERGUIDE_URL + "\n\n"
                    + "Command Summary:\n\n"

                    + "add\n"
                    + "Format: add n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS m/YYYY-MM-DD\n"
                    + "- Adds a new member.\n"
                    + "- Membership ID is automatically generated by the system.\n"
                    + "- Phone number must be 8 digits.\n"
                    + "- Expiry date must not be before today.\n\n"

                    + "list\n"
                    + "Format: list\n"
                    + "- Lists all members.\n\n"

                    + "delete\n"
                    + "Format: delete MEMBERSHIP_ID\n"
                    + "- Deletes an existing member by Membership ID.\n\n"

                    + "help\n"
                    + "Format: help\n"
                    + "- Shows the help window and User Guide link.\n\n"

                    + "find\n"
                    + "Format: find [id/|n/|p/|e/|a/|m/] [VALUE]\n"
                    + "- Searches using exactly one prefix.\n"
                    + "- ID, phone, email, and expiry date use exact match.\n"
                    + "- Address does not require exact match.\n\n"

                    + "edit\n"
                    + "Format: edit MEMBERSHIP_ID [n/NAME] [p/PHONE] [e/EMAIL] [a/ADDRESS] [m/YYYY-MM-DD]\n"
                    + "- Edits one or more fields of an existing member.\n"
                    + "- Membership ID cannot be edited.\n\n"

                    + "exit\n"
                    + "Format: exit\n"
                    + "- Exits the application.\n\n"

                    + "expiry\n"
                    + "Format: expiry DAYS\n"
                    + "- Shows members expiring within DAYS.\n"
                    + "- 0 means expiring today / last day.\n\n"

                    + "check\n"
                    + "Format: check MEMBERSHIP_ID\n"
                    + "- Directly checks membership validity by Membership ID.\n\n"

                    + "sort\n"
                    + "Format: sort [id/|n/|p/|e/|a/|m/] [asc|dcs]\n"
                    + "- Sorts members by one field in ascending or descending order.";

    private static final Logger logger = LogsCenter.getLogger(HelpWindow.class);
    private static final String FXML = "HelpWindow.fxml";

    @FXML
    private Button copyButton;

    @FXML
    private Label helpMessage;

    /**
     * Creates a new HelpWindow.
     *
     * @param root Stage to use as the root of the HelpWindow.
     */
    public HelpWindow(Stage root) {
        super(FXML, root);
        helpMessage.setText(HELP_MESSAGE);
    }

    /**
     * Creates a new HelpWindow.
     */
    public HelpWindow() {
        this(new Stage());
    }

    /**
     * Shows the help window.
     * @throws IllegalStateException
     *     <ul>
     *         <li>
     *             if this method is called on a thread other than the JavaFX Application Thread.
     *         </li>
     *         <li>
     *             if this method is called during animation or layout processing.
     *         </li>
     *         <li>
     *             if this method is called on the primary stage.
     *         </li>
     *         <li>
     *             if {@code dialogStage} is already showing.
     *         </li>
     *     </ul>
     */
    public void show() {
        logger.fine("Showing help page about the application.");
        getRoot().show();
        getRoot().centerOnScreen();
    }

    /**
     * Returns true if the help window is currently being shown.
     */
    public boolean isShowing() {
        return getRoot().isShowing();
    }

    /**
     * Hides the help window.
     */
    public void hide() {
        getRoot().hide();
    }

    /**
     * Focuses on the help window.
     */
    public void focus() {
        getRoot().requestFocus();
    }

    /**
     * Copies the URL to the user guide to the clipboard.
     */
    @FXML
    private void copyUrl() {
        final Clipboard clipboard = Clipboard.getSystemClipboard();
        final ClipboardContent url = new ClipboardContent();
        url.putString(USERGUIDE_URL);
        clipboard.setContent(url);
    }
}
